spring:
  jpa:
    show-sql: false
    hibernate:
      default_schema: public
      ddl-auto: none
      auto: none
  datasource:
    url: jdbc:mysql://172.22.0.1:3306/root?allowpublickeyretrieval=true&usessl=false
    username: root
    password: Root@2021
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 8070