version: '2'
services:
  smartchoice-fapi:
    container_name: smartchoice-fapi
    image: smartchoice-api:latest
    ports:
      - 8080:8080
    environment:
      - MYSQL_IP=172.22.0.2 # change mysql ip here
      - CRAWLER_IP=172.22.0.3 # change crawler ip here
      - LOG_IP=172.22.0.4 # change log ip here





