spring:
  jpa:
    show-sql: false
    hibernate:
      default_schema: public
      ddl-auto: none
      auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/root?allowpublickeyretrieval=true&usessl=false
    username: root
    password: Root@2021
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog-master.xml
    database-change-log-lock-table: LIQUIBASECHANGELOGLOCK # Name of table to use for tracking concurrent Liquibase usage.
    database-change-log-table: LIQUIBASECHANGELOG # Name of table to use for tracking change history.
    drop-first: false