name: build logs

# Controls when the action will run.
on:
  # Triggers the workflow on push or push and pull request events
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "testBE"
  testBE:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.number }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Setup jdk
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Chmod mvnw
        run: chmod +x ./smartchoice-fapi/mvnw

      - name: Cache maven dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maventestBE-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maventestBE-

      - name: Cache sonar dependencies
        uses: actions/cache@v2.1.3
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonartestBE-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-sonartestBE-

      - name: Clean test
        run: cd smartchoice-log && ./mvnw clean verify sonar:sonar -Dsonar.branch.name=$BRANCH_NAME